In [3]:
import numpy as np

In [4]:
v1 = np.array([1,2,3,4])
print(v1)

[1 2 3 4]


In [7]:
#연속되거나 일정한 규칙을 가진 숫자
#0부터 4까지 생성됨
v1 = np.arange(5)
print(v1)

#연속되거나 일정한 규칙을 가진 숫자, 데이터 형태 지정
v2 = np.arange(1,10,2, dtype=int)
v3 = np.arange(3.5,10.5,2,dtype = float)
print(v2)
print(v3)

#제곱값 생성
v4 = np.arange(1,10,2)**2
print(v4)

#세제곱값 생성
v5 = np.arange(1,10,2)**3
print(v5)

[0 1 2 3 4]
[1 3 5 7 9]
[3.5 5.5 7.5 9.5]
[ 1  9 25 49 81]
[  1  27 125 343 729]


In [8]:
#행렬 만들기
v1 = np.arange(12)
print(v1)
v2 = v1.reshape(2,6)
print(v2)
v3=v1.reshape(2,6,order="F")
print(v3)

#order = T는 가로부터 할당, F는 세로부터 할당

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [9]:
#행렬계산
v1 = np.arange(1,5).reshape(2,2)
print(np.add(v1,v1)) #덧셈
print(np.subtract(v1,v1)) #뺼셈
print(np.multiply(v1,v1)) #곱셈
print(np.dot(v1,v1)) #행렬연산

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [10]:
#다차원 행렬 만들기
v1 = np.arange(12)
print(v1)
v2 = v1.reshape(2,3,2,order='F')
print(v2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [11]:
#다차원 배열에서 요소의 최대값 최소값 반환
v3 = np.arange(3.5,10.5,2,dtype=float)
print(v3)
v4 = np.arange(1,5).reshape(2,2)
print(v4)
print(np.amax(v3))
print(np.amin(v4))
print(v3.dtype)
print(v4.dtype)

[3.5 5.5 7.5 9.5]
[[1 2]
 [3 4]]
9.5
1
float64
int32
