In [1]:
#분류
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
data = pd.read_csv("breast-cancer-wisconsin.csv",encoding='utf-8')
X = data[data.columns[1:10]]
y = data[["Class"]]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,stratify=y,random_state=42)

#min-max

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)

X_scaled_train = scaler.transform(X_train)
X_scaled_test = scaler.transform(X_test)

In [5]:
from sklearn.ensemble import AdaBoostClassifier
model = AdaBoostClassifier(n_estimators = 100, random_state = 0)
model.fit(X_scaled_train,y_train)
pred_train = model.predict(X_scaled_train)
model.score(X_scaled_train,y_train)

1.0

In [6]:
from sklearn.metrics import confusion_matrix
confusion_train = confusion_matrix(y_train,pred_train)
print("훈련데이터 오차행렬 :\n",confusion_train)

훈련데이터 오차행렬 :
 [[333   0]
 [  0 179]]


In [8]:
from sklearn.metrics import classification_report
cfreport_train = classification_report(y_train,pred_train)
print("분류 예측 레포트 :\n",cfreport_train)

분류 예측 레포트 :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       333
           1       1.00      1.00      1.00       179

    accuracy                           1.00       512
   macro avg       1.00      1.00      1.00       512
weighted avg       1.00      1.00      1.00       512



In [9]:
pred_test = model.predict(X_scaled_test)
model.score(X_scaled_test,y_test)

0.9532163742690059

In [10]:
confusion_test = confusion_matrix(y_test,pred_test)
print("테스트 데이터 오차행렬 :\n",confusion_test)

테스트 데이터 오차행렬 :
 [[106   5]
 [  3  57]]


In [11]:
cfreport_test = classification_report(y_test,pred_test)
print("분류 예측 레포트 :\n",cfreport_test)

분류 예측 레포트 :
               precision    recall  f1-score   support

           0       0.97      0.95      0.96       111
           1       0.92      0.95      0.93        60

    accuracy                           0.95       171
   macro avg       0.95      0.95      0.95       171
weighted avg       0.95      0.95      0.95       171



In [12]:
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier(n_estimators = 100, learning_rate=1.0,max_depth=1,random_state=0)
model.fit(X_scaled_train,y_train)
pred_train = model.predict(X_scaled_train)
model.score(X_scaled_train,y_train)

1.0

In [13]:
confusion_train = confusion_matrix(y_train,pred_train)
print("훈련데이터 오차행렬 : \n",confusion_train)

훈련데이터 오차행렬 : 
 [[333   0]
 [  0 179]]


In [14]:
pred_test = model.predict(X_scaled_test)
model.score(X_scaled_test,y_test)

0.9649122807017544

In [15]:
confusion_test = confusion_matrix(y_test,pred_test)
print("테스트 데이터 오차행렬 :\n",confusion_test)

테스트 데이터 오차행렬 :
 [[106   5]
 [  1  59]]


In [16]:
#회귀
import pandas as pd
data2 = pd.read_csv("house_price.csv",encoding='utf-8')
X = data2[data2.columns[1:5]]
y = data2[["house_value"]]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_scaled_train = scaler.transform(X_train)
X_scaled_test = scaler.transform(X_test)

In [17]:
from sklearn.ensemble import AdaBoostRegressor
model = AdaBoostRegressor(random_state=0,n_estimators=100)
model.fit(X_scaled_train,y_train)
pred_train = model.predict(X_scaled_train)
model.score(X_scaled_train,y_train)

0.4353130085971758

In [18]:
pred_test = model.predict(X_scaled_test)
model.score(X_scaled_test,y_test)

0.43568387094087124

In [23]:
import numpy as np
from sklearn.metrics import mean_squared_error
MSE_train = mean_squared_error(y_train,pred_train)
MSE_test = mean_squared_error(y_test,pred_test)

print("훈련 데이터 : ",np.sqrt(MSE_train))
print("테스트 데이터 : ",np.sqrt(MSE_test))

훈련 데이터 :  71722.42012035428
테스트 데이터 :  71816.41231019037


In [24]:
from sklearn.ensemble import GradientBoostingRegressor
model = GradientBoostingRegressor(random_state=0)

model.fit(X_scaled_train,y_train)
pred_train = model.predict(X_scaled_train)
model.score(X_scaled_train,y_train)

0.6178724780500952

In [25]:
pred_test = model.predict(X_scaled_test)
model.score(X_scaled_test,y_test)

0.5974112241813845

In [26]:
import numpy as np
from sklearn.metrics import mean_squared_error

MSE_train = mean_squared_error(y_train,pred_train)
MSE_test = mean_squared_error(y_test,pred_test)

print("훈련 데이터 : ",np.sqrt(MSE_train))
print("테스트 데이터 : ",np.sqrt(MSE_test))

훈련 데이터 :  59000.433545962376
테스트 데이터 :  60658.72886338227
