In [1]:
#분류
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
data = pd.read_csv("breast-cancer-wisconsin.csv",encoding='utf-8')
X = data[data.columns[1:10]]
y = data[["Class"]]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,stratify=y,random_state=42)

#min-max

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)

X_scaled_train = scaler.transform(X_train)
X_scaled_test = scaler.transform(X_test)

In [2]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier


logit_model = LogisticRegression(random_state=42)
rnf_model = RandomForestClassifier(random_state=42)
svm_model = SVC(random_state = 42)

voting_hard = VotingClassifier(estimators=[('lr',logit_model),('rf',rnf_model),('svc',svm_model)],voting='hard')
voting_hard.fit(X_scaled_train,y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(random_state=42)),
                             ('rf', RandomForestClassifier(random_state=42)),
                             ('svc', SVC(random_state=42))])

In [4]:
from sklearn.metrics import accuracy_score

for clf in (logit_model,rnf_model,svm_model,voting_hard):
    clf.fit(X_scaled_train,y_train)
    y_pred = clf.predict(X_scaled_test)
    print(clf.__class__.__name__,accuracy_score(y_test,y_pred))

LogisticRegression 0.9590643274853801
RandomForestClassifier 0.9649122807017544
SVC 0.9649122807017544
VotingClassifier 0.9649122807017544


In [5]:
from sklearn.metrics import confusion_matrix
log_pred_train = logit_model.predict(X_scaled_train)
log_confusion_train = confusion_matrix(y_train,log_pred_train)
print("로지스틱 분류기 훈련데이터 오차행렬 :\n",log_confusion_train)

log_pred_test = logit_model.predict(X_scaled_test)
log_confusion_test = confusion_matrix(y_test,log_pred_test)
print("로지스틱 분류기 테스트데이터 오차행렬 :\n",log_confusion_test)

로지스틱 분류기 훈련데이터 오차행렬 :
 [[328   5]
 [  9 170]]
로지스틱 분류기 테스트데이터 오차행렬 :
 [[106   5]
 [  2  58]]


In [7]:
svm_pred_train = svm_model.predict(X_scaled_train)
svm_confusion_train = confusion_matrix(y_train,svm_pred_train)
print("서포트 벡터머신 분류기 훈련 데이터 오차행렬 :\n",svm_confusion_train)

svm_pred_test = svm_model.predict(X_scaled_test)
svm_confusion_test = confusion_matrix(y_test,svm_pred_test)
print("서포트 벡터머신 분류기 테스트 데이터 오차행렬 :\n",svm_confusion_test)

서포트 벡터머신 분류기 훈련 데이터 오차행렬 :
 [[329   4]
 [  4 175]]
서포트 벡터머신 분류기 테스트 데이터 오차행렬 :
 [[106   5]
 [  1  59]]


In [10]:
rnf_pred_train = rnf_model.predict(X_scaled_train)
rnf_confusion_train = confusion_matrix(y_train,rnf_pred_train)
print("랜덤포레스트 분류기 훈련 데이터 오차행렬 :\n",rnf_confusion_train)

rnf_pred_test = rnf_model.predict(X_scaled_test)
rnf_confusion_test = confusion_matrix(y_test,rnf_pred_test)
print("랜덤포레스트 분류기 테스트 데이터 오차행렬 :\n",rnf_confusion_test)

랜덤포레스트 분류기 훈련 데이터 오차행렬 :
 [[333   0]
 [  0 179]]
랜덤포레스트 분류기 테스트 데이터 오차행렬 :
 [[106   5]
 [  1  59]]


In [14]:
voting_pred_train = voting_hard.predict(X_scaled_train)
voting_confusion_train = confusion_matrix(y_train,voting_pred_train)
print("투표 분류기 분류기 훈련데이터 오차행렬 :\n",voting_confusion_train)

voting_pred_test = voting_hard.predict(X_scaled_test)
voting_confusion_test = confusion_matrix(y_test,voting_pred_test)
print("투표 분류기 분류기 테스트데이터 오차행렬 :\n",voting_confusion_test)

투표 분류기 분류기 훈련데이터 오차행렬 :
 [[329   4]
 [  4 175]]
투표 분류기 분류기 테스트데이터 오차행렬 :
 [[106   5]
 [  1  59]]


In [26]:
#약한 학습기 soft learner

logit_model = LogisticRegression(random_state = 42)
rnf_model = RandomForestClassifier(random_state = 42)
svm_model = SVC(random_state = 42, probability=True )
voting_soft = VotingClassifier(estimators=[('lr',logit_model),('rf',rnf_model),('svm',svm_model)],voting='soft')
voting_soft.fit(X_scaled_train,y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(random_state=42)),
                             ('rf', RandomForestClassifier(random_state=42)),
                             ('svm', SVC(probability=True, random_state=42))],
                 voting='soft')

In [27]:
from sklearn.metrics import accuracy_score
for clf in (logit_model,rnf_model,svm_model,voting_soft):
    clf.fit(X_scaled_train,y_train)
    y_pred = clf.predict(X_scaled_test)
    print(clf.__class__.__name__,accuracy_score(y_test,y_pred))

LogisticRegression 0.9590643274853801
RandomForestClassifier 0.9649122807017544
SVC 0.9649122807017544
VotingClassifier 0.9649122807017544


In [28]:
#회귀
import pandas as pd
data2 = pd.read_csv("house_price.csv",encoding='utf-8')
X = data2[data2.columns[1:5]]
y = data2[["house_value"]]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_scaled_train = scaler.transform(X_train)
X_scaled_test = scaler.transform(X_test)

In [32]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import VotingRegressor

linear_model = LinearRegression()
rnf_model = RandomForestRegressor(random_state=42)
voting_regressor = VotingRegressor(estimators=[('lr',linear_model),('rf',rnf_model)])
voting_regressor.fit(X_scaled_train, y_train)

VotingRegressor(estimators=[('lr', LinearRegression()),
                            ('rf', RandomForestRegressor(random_state=42))])

In [33]:
pred_train = voting_regressor.predict(X_scaled_train)
voting_regressor.score(X_scaled_train, y_train)

0.7962532705428835

In [35]:
pred_test = voting_regressor.predict(X_scaled_test)
voting_regressor.score(X_scaled_test,y_test)

0.5936371957936409

In [36]:
import numpy as np
from sklearn.metrics import mean_squared_error

MSE_train = mean_squared_error(y_train,pred_train)
MSE_test = mean_squared_error(y_test,pred_test)

print("훈련 데이터 RMSE :",np.sqrt(MSE_train))
print("테스트 데이터 RMSE : ",np.sqrt(MSE_test))

훈련 데이터 RMSE : 43082.050654857834
테스트 데이터 RMSE :  60942.38524353489
